"""Regenerate ``emtk/colormaps.json`` -- the colour tables :mod:`emtk.colormaps` reads.

Developer tool, not shipped behaviour. Run it only to add a map::

    python tools/build_colormaps.py --pyqtgraph-maps <dir> [--matplotlib]

Two sources, each recorded per map in the output (``"source"``):

* ``--pyqtgraph-maps``: a folder of pyqtgraph's map files (``*.csv`` RGB stops
  in 0..1, ``*.hex`` palettes): ``pyqtgraph/colors/maps`` of pyqtgraph 0.14. viridis/magma/inferno/plasma/cividis are CC0, the CET maps
  CC-BY 4.0 (Peter Kovesi), turbo Apache-2.0 (Google); see
  ``licenses/colormaps.txt``.
* ``--matplotlib``: the colour names (CSS4, one-letter, ``C0``..``C9``) and
  the remaining classic maps (gray, hot, jet, RdBu, ...),
  sampled at 256 points from matplotlib's definitions. matplotlib is used here
  as a *source of numbers* only; emtk never imports it.

Stops are stored as ``#rrggbb`` -- the 8-bit precision every consumer reads
them at -- and are interpolated linearly at lookup time, as pyqtgraph does.
"""

from __future__ import annotations

import argparse
import json
import pathlib

#: Classic maps taken from matplotlib (not in pyqtgraph's set).
MATPLOTLIB_MAPS = (
    "gray", "Greys", "binary", "bone", "copper", "pink", "hot", "afmhot",
    "spring", "summer", "autumn", "winter", "cool", "rainbow", "jet", "hsv",
    "twilight", "RdBu", "coolwarm", "bwr", "seismic", "Spectral", "PuOr",
    "gist_earth", "terrain", "Blues", "Reds", "Greens", "Purples", "Oranges",
    "YlOrRd", "tab10", "tab20",
)

#: Qualitative maps: lookups pick the nearest colour, never a blend.
QUALITATIVE = {"tab10", "tab20", "PAL-relaxed", "PAL-relaxed_bright"}


def _hex(rgb) -> str:
    # Half rounds *up*, as pyqtgraph's reader quantises: Python's round() is
    # half-to-even and moved two CET-L9 entries by one step.
    return "#" + "".join(f"{max(0, min(255, int(float(c) * 255 + 0.5))):02x}" for c in rgb[:3])


def _read_pyqtgraph(path: pathlib.Path) -> list[str]:
    """Stops of one pyqtgraph map file, as ``pyqtgraph.colormap`` reads them."""
    stops = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith(";"):
            continue
        colour = line.split(";", 1)[0].strip()
        if not colour:
            continue
        if path.suffix.lower() == ".hex":
            text = colour.lstrip("#")
            if len(text) == 3:
                text = "".join(2 * c for c in text)
            if len(text) >= 6:
                stops.append("#" + text[:6].lower())
        else:
            parts = colour.split(",")
            if len(parts) >= 3:
                stops.append(_hex([float(p) for p in parts[:3]]))
    return stops


def _named_colours() -> dict[str, str]:
    """The colour names :func:`emtk.colormaps.to_rgba` accepts, as ``#rrggbb``.

    The W3C CSS4 names (a public standard), the one-letter shorthands
    (``"r"``, ``"k"``, ...) and the ``"C0"``..``"C9"`` cycle, which is the
    tab10 palette -- the spellings plot code written against matplotlib uses.
    """
    import matplotlib.colors as mcolors

    named = {name: value.lower() for name, value in mcolors.CSS4_COLORS.items()}
    named.update({k: _hex(v) for k, v in mcolors.BASE_COLORS.items()})
    tab10 = [mcolors.TABLEAU_COLORS[k] for k in mcolors.TABLEAU_COLORS]
    named.update({f"C{i}": value.lower() for i, value in enumerate(tab10)})
    named.update({k: v.lower() for k, v in mcolors.TABLEAU_COLORS.items()})
    return dict(sorted(named.items()))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--pyqtgraph-maps", type=pathlib.Path, required=True)
    parser.add_argument("--matplotlib", action="store_true")
    parser.add_argument(
        "--out", type=pathlib.Path,
        default=pathlib.Path(__file__).resolve().parent.parent / "emtk" / "colormaps.json",
    )
    args = parser.parse_args()

    maps: dict[str, dict] = {}
    for path in sorted(args.pyqtgraph_maps.iterdir()):
        if path.suffix.lower() not in (".csv", ".hex"):
            continue
        maps[path.stem] = {"source": "pyqtgraph", "stops": _read_pyqtgraph(path)}
    if args.matplotlib:
        import matplotlib
        import numpy as np

        for name in MATPLOTLIB_MAPS:
            cmap = matplotlib.colormaps[name]
            n = cmap.N if name in QUALITATIVE else 256
            colours = cmap(np.arange(n) if name in QUALITATIVE else np.linspace(0.0, 1.0, 256))
            maps[name] = {"source": "matplotlib", "stops": [_hex(c) for c in colours]}
    for name, entry in maps.items():
        if name in QUALITATIVE:
            entry["qualitative"] = True
    document = {
        "about": "Colour tables for emtk.colormaps; generated by tools/build_colormaps.py. "
                 "Licences: licenses/colormaps.txt.",
        "maps": dict(sorted(maps.items(), key=lambda kv: kv[0].lower())),
        "named": _named_colours() if args.matplotlib else {},
    }
    args.out.write_text(json.dumps(document, separators=(",", ":")) + "\n", encoding="utf-8")
    print(f"{len(maps)} maps -> {args.out}")


if __name__ == "__main__":
    main()
