"""emtk -- Dear ImGui for Python, drawn through one painter.

An immediate-mode GUI toolkit with nothing to compile: six painter
operations, no toolkit, no native extension, no build step. The same widget
code runs on a desktop GL context, in a browser under Pyodide, and in a test
with no window at all.

``ImGui::Button`` is ``emtk.button``; the translation is mechanical and every
published name of the reference has one. See ``README.md`` for the whole of
it, and :mod:`emtk.im` for the API a program calls.

The toolkit grew inside `chimol <https://github.com/tpeulen/chimol>`_, a
molecular viewer, and moved out once its tests, examples and documentation
stood on their own.
"""
from __future__ import annotations

# Eager, and a submodule rather than a name: a host reaches for
# `emtk.redraw.content_key` while deciding whether to keep last frame's
# vertices, which is the wrong moment to discover a lazy import. It costs one
# small module with no dependencies of its own.
from . import redraw
from .widgets.axis import Axis, nice_ticks
from .widgets.markers import MARKERS, draw_marker
from .painter import (
    ALIGN_CENTER,
    ALIGN_HCENTER,
    ALIGN_LEFT,
    ALIGN_RIGHT,
    ALIGN_VCENTER,
    Colour,
    Painter,
)
from .widgets.plot import DEEP_PALETTE, Plot, begin_plot
from .widgets.basic import (
    Button,
    Checkbox,
    ColorEdit4,
    Combo,
    Histogram,
    InputInt,
    ListBox,
    PlotLines,
    ProgressBar,
    RadioGroup,
    ScrollBar,
    Separator,
    SliderFloat,
    Table,
    Tabs,
    TextInput,
    Toggle,
    Tooltip,
    TreeNode,
    fit_text,
)

__all__ = [
    "ALIGN_CENTER",
    "ALIGN_HCENTER",
    "ALIGN_LEFT",
    "ALIGN_RIGHT",
    "ALIGN_VCENTER",
    "Colour",
    "Painter",
    "Button",
    "Checkbox",
    "ColorEdit4",
    "Combo",
    "Histogram",
    "InputInt",
    "ListBox",
    "PlotLines",
    "ProgressBar",
    "RadioGroup",
    "ScrollBar",
    "Separator",
    "SliderFloat",
    "Table",
    "Tabs",
    "TextInput",
    "Toggle",
    "Tooltip",
    "TreeNode",
    "fit_text",
    "Axis",
    "nice_ticks",
    "MARKERS",
    "draw_marker",
    "DEEP_PALETTE",
    "Plot",
    "begin_plot",
]

#: The ported families, by module name. Kept as data because it is what the
#: gallery, the documentation generator and the atlas guard all enumerate --
#: three places that would otherwise each keep their own list and each miss a
#: different new module.
CONTROL_MODULES = (
    "widgets.basic",
    "widgets.text",
    "widgets.combo",
    "widgets.buttons",
    "widgets.sliders",
    "widgets.drag",
    "widgets.inputs",
    "widgets.color",
    "widgets.selection",
    "widgets.list_view",
    "widgets.menus",
    "widgets.tabs",
    "widgets.splitter",
    "widgets.tables",
    "widgets.dragdrop",
    "layout",
    "widgets.text_editor",
    "widgets.memory_editor",
    "control",
    "widgets.axis",
    "widgets.markers",
    "widgets.plot",
    "widgets.circle",
    "drawlist",
    # Pixels a painter can draw. A program that shows a picture needs one,
    # and the alternative is a graphics API in the application.
    "texture",
    "im",
    "events",
    "keys",
    "router",
    # The test doubles belong to the library too: a widget you cannot exercise
    # without the application it lives in is not portable, whatever its
    # imports say.
    "testing",
)

#: Modules that belong to the library but are **not** flattened into the
#: package namespace: you reach them as ``from emtk import nodes`` and call
#: ``nodes.begin_node()``.
#:
#: The distinction is not about collisions, though there are some. A node
#: editor has its own colour enum, its own style struct and its own canvas,
#: and they are *parallel* to the toolkit's rather than part of it -- which is
#: why the reference spells them ``ImNodesCol_`` beside ``ImGuiCol_`` instead
#: of adding entries to one. Lifting ``nodes.Col`` to ``emtk.Col`` would put
#: the node editor's palette where every widget's palette already lives, and
#: the name that lost would do so silently.
#:
#: They are enumerated here rather than left out entirely because the
#: documentation build and the atlas guard walk the library by module, and a
#: module in neither list is one nothing checks.
NAMESPACED_MODULES = (
    # A graph, as an editor rather than a picture of one: nodes, pins, links
    # and a pannable grid. Modelled on Nelarius/imnodes -- ``nodes.py``'s
    # docstring records the five candidates that were measured first.
    "nodes",
)

#: Every lazily-exported name and the family module that owns it. Generated
#: by ``tools/gen_names.py`` (``--check`` in the tests, so it cannot go
#: stale). Looked up in O(1) instead of importing every family until one
#: answers -- which is what ``__getattr__`` used to do.
#: emtk's own version. It is a library with its own tests, examples and docs
#: (see ``README.md``), so it says what it is rather than borrowing the
#: application's number.
__version__ = "0.1.1"

#: The Dear ImGui release whose published API ``im`` is checked against. The
#: list of names lives in ``tests/emtk/imgui_api.txt``, taken from this
#: version's ``imgui.h``; every one of them translates.
IMGUI_VERSION = "1.93.0"


_NAME_TO_MODULE: dict[str, str] = {
    "ALT_MODIFIER": "events",
    "AcceptFlags": "widgets.dragdrop",
    "Action": "widgets.text_editor",
    "ArrowButton": "widgets.buttons",
    "Axis": "widgets.axis",
    "BORDER_SIZE": "widgets.tables",
    "BackendFlags": "im",
    "BracketPair": "widgets.text_editor",
    "Bracketeer": "widgets.text_editor",
    "BufferSource": "widgets.memory_editor",
    "Bullet": "widgets.text",
    "BulletText": "widgets.text",
    "Button": "widgets.basic",
    "ButtonFlags": "im",
    "ButtonState": "widgets.buttons",
    "CASCADE_FRACTION": "im",
    "CASCADE_SIZE": "im",
    "CASCADE_STEP": "im",
    "COMBO_HEIGHT_LARGE": "widgets.combo",
    "COMBO_HEIGHT_LARGEST": "widgets.combo",
    "COMBO_HEIGHT_MASK": "widgets.combo",
    "COMBO_HEIGHT_REGULAR": "widgets.combo",
    "COMBO_HEIGHT_SMALL": "widgets.combo",
    "COMBO_NONE": "widgets.combo",
    "COMBO_NO_ARROW_BUTTON": "widgets.combo",
    "COMBO_NO_PREVIEW": "widgets.combo",
    "COMBO_POPUP_ALIGN_LEFT": "widgets.combo",
    "COMBO_WIDTH_FIT_PREVIEW": "widgets.combo",
    "CONTROL_MODIFIER": "events",
    "Capture": "router",
    "Checkbox": "widgets.basic",
    "CheckboxFlags": "widgets.buttons",
    "ChildFlags": "im",
    "CirclePlot": "widgets.circle",
    "CircleSector": "widgets.circle",
    "Col": "im",
    "CollapsingHeader": "widgets.selection",
    "ColorButton": "widgets.color",
    "ColorEdit4": "widgets.basic",
    "ColorEditFlags": "im",
    "ColorEditRGB": "widgets.color",
    "ColorEditRGBA": "widgets.color",
    "ColorPicker3": "widgets.color",
    "ColorPicker4": "widgets.color",
    "ColorState": "widgets.color",
    "Colorizer": "widgets.text_editor",
    "Column": "widgets.tables",
    "Combo": "widgets.basic",
    "ComboBox": "widgets.combo",
    "ComboFlags": "im",
    "ComboPress": "widgets.combo",
    "Cond": "im",
    "ConfigFlags": "im",
    "Consumed": "router",
    "Context": "im",
    "Control": "control",
    "Cursor": "widgets.text_editor",
    "Cursors": "widgets.text_editor",
    "DARK_PALETTE": "widgets.text_editor",
    "DELAY_NONE": "widgets.dragdrop",
    "DELAY_NORMAL": "widgets.dragdrop",
    "DELAY_SHORT": "widgets.dragdrop",
    "DIR_DOWN": "widgets.buttons",
    "DIR_LEFT": "widgets.buttons",
    "DIR_RIGHT": "widgets.buttons",
    "DIR_UP": "widgets.buttons",
    "DRAG_SPEED_DEFAULT_RATIO": "widgets.drag",
    "DRAG_THRESHOLD": "widgets.drag",
    "DRAW_FLAGS_CLOSED": "drawlist",
    "DRAW_FLAGS_ROUND_CORNERS_ALL": "drawlist",
    "DRAW_FLAGS_ROUND_CORNERS_NONE": "drawlist",
    "DataTable": "widgets.tables",
    "DataType": "im",
    "DelayedTooltip": "widgets.dragdrop",
    "Dir": "im",
    "Document": "widgets.text_editor",
    "DragDropContext": "widgets.dragdrop",
    "DragDropFlags": "im",
    "DragDropSource": "widgets.dragdrop",
    "DragDropTarget": "widgets.dragdrop",
    "DragFloat": "widgets.drag",
    "DragFloatN": "widgets.drag",
    "DragFloatRange2": "widgets.drag",
    "DragInt": "widgets.drag",
    "DragIntN": "widgets.drag",
    "DragIntRange2": "widgets.drag",
    "DrawFlags": "im",
    "DrawList": "drawlist",
    "EditorConfig": "widgets.text_editor",
    "Event": "router",
    "FIXED_GLYPH_W": "testing",
    "FIXED_LINE_H": "testing",
    "FRAME_PAD": "widgets.combo",
    "FocusedFlags": "im",
    "GRAB_MIN_SIZE": "widgets.sliders",
    "GRAB_PADDING": "widgets.sliders",
    "Handler": "router",
    "Histogram": "widgets.basic",
    "HoveredFlags": "im",
    "INNER_SPACING": "widgets.combo",
    "IO": "im",
    "ImWidget": "im",
    "InputDouble": "widgets.inputs",
    "InputFloat": "widgets.inputs",
    "InputFloat2": "widgets.inputs",
    "InputFloat3": "widgets.inputs",
    "InputFloat4": "widgets.inputs",
    "InputInt": "widgets.basic",
    "InputInt2": "widgets.inputs",
    "InputInt3": "widgets.inputs",
    "InputInt4": "widgets.inputs",
    "InputScalar": "widgets.inputs",
    "InputScalarN": "widgets.inputs",
    "InputTextFlags": "im",
    "InputTextMultiline": "widgets.inputs",
    "InputTextWithHint": "widgets.inputs",
    "InvisibleButton": "widgets.buttons",
    "ItemFlags": "im",
    "KEY_BACKSPACE": "keys",
    "KEY_DELETE": "keys",
    "KEY_DOWN": "keys",
    "KEY_END": "keys",
    "KEY_ENTER": "keys",
    "KEY_ESCAPE": "keys",
    "KEY_F1": "keys",
    "KEY_F10": "keys",
    "KEY_F11": "keys",
    "KEY_F12": "keys",
    "KEY_F2": "keys",
    "KEY_F3": "keys",
    "KEY_F4": "keys",
    "KEY_F5": "keys",
    "KEY_F6": "keys",
    "KEY_F7": "keys",
    "KEY_F8": "keys",
    "KEY_F9": "keys",
    "KEY_HOME": "keys",
    "KEY_INSERT": "keys",
    "KEY_LEFT": "keys",
    "KEY_PAGE_DOWN": "keys",
    "KEY_PAGE_UP": "keys",
    "KEY_RETURN": "keys",
    "KEY_RIGHT": "keys",
    "KEY_TAB": "keys",
    "KEY_UP": "keys",
    "Key": "im",
    "KeyEvent": "events",
    "LEFT_BUTTON": "events",
    "LIGHT_PALETTE": "widgets.text_editor",
    "LOG_SLIDER_DEADZONE": "widgets.sliders",
    "LabelText": "widgets.text",
    "Language": "widgets.text_editor",
    "Layer": "router",
    "Layout": "layout",
    "LayoutStyle": "layout",
    "Line": "widgets.text_editor",
    "LineState": "widgets.text_editor",
    "ListBox": "widgets.basic",
    "ListClipper": "im",
    "ListRows": "widgets.list_view",
    "ListView": "widgets.list_view",
    "MARKERS": "widgets.markers",
    "MARK_SCALE": "widgets.menus",
    "MAX_TAB_WIDTH_EM": "widgets.tabs",
    "META_MODIFIER": "events",
    "MIDDLE_BUTTON": "events",
    "MemoryEditor": "widgets.memory_editor",
    "MemorySource": "widgets.memory_editor",
    "Menu": "widgets.menus",
    "MenuBar": "widgets.menus",
    "MenuItem": "widgets.menus",
    "MouseButton": "im",
    "MouseCursor": "im",
    "MultiSelectIO": "im",
    "MultiSelectState": "widgets.selection",
    "NO_BUTTON": "events",
    "NO_MODIFIER": "events",
    "OVERLAP": "widgets.menus",
    "OverlayStack": "router",
    "PAD": "widgets.combo",
    "PAD_X": "widgets.tabs",
    "PLACE_CASCADE": "im",
    "PLACE_FRAME": "im",
    "PREVIEW_TYPES": "widgets.memory_editor",
    "Pass": "router",
    "Payload": "widgets.dragdrop",
    "PixelPainter": "testing",
    "PlatformIO": "im",
    "Plot": "widgets.plot",
    "PlotLines": "widgets.basic",
    "Point": "events",
    "PointerEvent": "events",
    "Popup": "widgets.menus",
    "PopupFlags": "im",
    "PopupModal": "widgets.menus",
    "PopupPress": "widgets.menus",
    "Pos": "widgets.text_editor",
    "ProgressBar": "widgets.basic",
    "RESIZE_HALF_THICKNESS": "widgets.tables",
    "RIGHT_BUTTON": "events",
    "ROW_SCALE": "widgets.combo",
    "RadioButton": "widgets.buttons",
    "RadioGroup": "widgets.basic",
    "RecordingPainter": "testing",
    "Rect": "events",
    "Router": "router",
    "Row": "widgets.list_view",
    "RowModel": "widgets.list_view",
    "SELECTABLE_ALLOW_DOUBLE_CLICK": "widgets.selection",
    "SELECTABLE_DISABLED": "widgets.selection",
    "SELECTABLE_DONT_CLOSE_POPUPS": "widgets.selection",
    "SELECTABLE_NONE": "widgets.selection",
    "SELECTABLE_SPAN_ALL_COLUMNS": "widgets.selection",
    "SEPARATOR_SCALE": "widgets.menus",
    "SHIFT_MODIFIER": "events",
    "SHRINK_MIN_WIDTH": "widgets.tabs",
    "SIZING_FIXED_FIT": "widgets.tables",
    "SIZING_FIXED_SAME": "widgets.tables",
    "SIZING_STRETCH_PROP": "widgets.tables",
    "SIZING_STRETCH_SAME": "widgets.tables",
    "SORT_ASCENDING": "widgets.tables",
    "SORT_DESCENDING": "widgets.tables",
    "SORT_NONE": "widgets.tables",
    "SPACING": "widgets.menus",
    "STATIONARY_DELAY": "widgets.dragdrop",
    "ScrollBar": "widgets.basic",
    "Selectable": "widgets.selection",
    "SelectableFlags": "im",
    "SelectableList": "widgets.selection",
    "Separator": "widgets.basic",
    "SeparatorText": "widgets.text",
    "SliderAngle": "widgets.sliders",
    "SliderFlags": "im",
    "SliderFloat": "widgets.basic",
    "SliderFloatN": "widgets.sliders",
    "SliderInt": "widgets.sliders",
    "SliderIntN": "widgets.sliders",
    "SliderScalar": "widgets.sliders",
    "SliderScalarN": "widgets.sliders",
    "SmallButton": "widgets.buttons",
    "SortDirection": "im",
    "SortSpec": "widgets.tables",
    "SortSpecs": "im",
    "Splitter": "widgets.splitter",
    "Style": "im",
    "StyleVar": "im",
    "TAB_BAR_AUTO_SELECT_NEW_TABS": "widgets.tabs",
    "TAB_BAR_FITTING_POLICY_DEFAULT": "widgets.tabs",
    "TAB_BAR_FITTING_POLICY_MASK": "widgets.tabs",
    "TAB_BAR_FITTING_POLICY_RESIZE_DOWN": "widgets.tabs",
    "TAB_BAR_FITTING_POLICY_SCROLL": "widgets.tabs",
    "TAB_BAR_NONE": "widgets.tabs",
    "TAB_BAR_NO_CLOSE_WITH_MIDDLE_MOUSE_BUTTON": "widgets.tabs",
    "TAB_BAR_NO_TAB_LIST_SCROLLING_BUTTONS": "widgets.tabs",
    "TAB_BAR_REORDERABLE": "widgets.tabs",
    "TAB_BAR_TAB_LIST_POPUP_BUTTON": "widgets.tabs",
    "TAB_SPACING": "widgets.tabs",
    "TabBar": "widgets.tabs",
    "TabBarFlags": "im",
    "TabItem": "widgets.tabs",
    "TabItemButton": "widgets.tabs",
    "TabItemFlags": "im",
    "TabPress": "widgets.tabs",
    "Table": "widgets.basic",
    "TableBgTarget": "im",
    "TableColumnFlags": "im",
    "TableFlags": "im",
    "Tabs": "widgets.basic",
    "Text": "widgets.text",
    "TextColored": "widgets.text",
    "TextDisabled": "widgets.text",
    "TextEditor": "widgets.text_editor",
    "TextInput": "widgets.basic",
    "TextLink": "widgets.text",
    "TextWrapped": "widgets.text",
    "Texture": "texture",
    "Toggle": "widgets.basic",
    "Token": "widgets.text_editor",
    "Tooltip": "widgets.basic",
    "Transaction": "widgets.text_editor",
    "Transactions": "widgets.text_editor",
    "TreeItem": "widgets.list_view",
    "TreeNode": "widgets.basic",
    "TreeNodeFlags": "im",
    "TreeRows": "widgets.list_view",
    "TreeView": "widgets.list_view",
    "TypingSelect": "widgets.selection",
    "VSliderFloat": "widgets.sliders",
    "VSliderInt": "widgets.sliders",
    "Value": "widgets.text",
    "Verdict": "router",
    "Viewport": "im",
    "WIDTH_FIXED": "widgets.tables",
    "WIDTH_STRETCH": "widgets.tables",
    "WindowFlags": "im",
    "accept_drag_drop_payload": "im",
    "align_text_to_frame_padding": "im",
    "apply_from_text": "widgets.inputs",
    "arrow_button": "im",
    "assert_images_equal": "testing",
    "begin": "im",
    "begin_child": "im",
    "begin_circle": "widgets.circle",
    "begin_combo": "im",
    "begin_disabled": "im",
    "begin_docked": "im",
    "begin_drag_drop_source": "im",
    "begin_drag_drop_target": "im",
    "begin_group": "im",
    "begin_item_tooltip": "im",
    "begin_list_box": "im",
    "begin_main_menu_bar": "im",
    "begin_menu": "im",
    "begin_menu_bar": "im",
    "begin_multi_select": "im",
    "begin_plot": "widgets.plot",
    "begin_popup": "im",
    "begin_popup_context_item": "im",
    "begin_popup_context_void": "im",
    "begin_popup_context_window": "im",
    "begin_popup_modal": "im",
    "begin_tab_bar": "im",
    "begin_tab_item": "im",
    "begin_table": "im",
    "begin_tooltip": "im",
    "best_popup_pos": "widgets.menus",
    "bullet": "im",
    "bullet_text": "im",
    "bullet_text_v": "im",
    "button": "im",
    "button_from_canvas": "events",
    "button_from_dom": "events",
    "button_name": "events",
    "buttons_from_dom": "events",
    "calc_item_width": "im",
    "calc_text_size": "im",
    "checkbox": "im",
    "checkbox_flags": "im",
    "close_current_popup": "im",
    "col32": "im",
    "collapsing_header": "im",
    "color_button": "im",
    "color_convert_float4_to_u32": "im",
    "color_convert_hs_vto_rgb": "im",
    "color_convert_hsv_to_rgb": "im",
    "color_convert_rg_bto_hsv": "im",
    "color_convert_rgb_to_hsv": "im",
    "color_convert_u32_to_float4": "im",
    "color_edit3": "im",
    "color_edit4": "im",
    "color_picker3": "im",
    "color_picker4": "im",
    "columns": "im",
    "combo": "im",
    "create_context": "im",
    "debug_check_version_and_data_layout": "im",
    "debug_flash_style_color": "im",
    "debug_log": "im",
    "debug_log_v": "im",
    "debug_start_item_picker": "im",
    "debug_text_encoding": "im",
    "destroy_context": "im",
    "dock_builder_dock_window": "im",
    "dock_builder_split_node": "im",
    "dock_space": "im",
    "dock_space_over_viewport": "im",
    "drag_float": "im",
    "drag_float2": "im",
    "drag_float3": "im",
    "drag_float4": "im",
    "drag_float_range2": "im",
    "drag_int": "im",
    "drag_int2": "im",
    "drag_int3": "im",
    "drag_int4": "im",
    "drag_int_range2": "im",
    "drag_scalar": "im",
    "drag_scalar_n": "im",
    "draw_marker": "widgets.markers",
    "dummy": "im",
    "end": "im",
    "end_child": "im",
    "end_combo": "im",
    "end_disabled": "im",
    "end_docked": "im",
    "end_drag_drop_source": "im",
    "end_drag_drop_target": "im",
    "end_frame": "im",
    "end_group": "im",
    "end_list_box": "im",
    "end_main_menu_bar": "im",
    "end_menu": "im",
    "end_menu_bar": "im",
    "end_multi_select": "im",
    "end_popup": "im",
    "end_tab_bar": "im",
    "end_tab_item": "im",
    "end_table": "im",
    "end_tooltip": "im",
    "fit_text": "widgets.basic",
    "floats_to_rgba": "widgets.color",
    "format_precision": "widgets.inputs",
    "frame": "im",
    "get_allocator_functions": "im",
    "get_background_draw_list": "im",
    "get_clipboard_text": "im",
    "get_color_u32": "im",
    "get_column_index": "im",
    "get_column_offset": "im",
    "get_column_width": "im",
    "get_column_width_of": "im",
    "get_columns_count": "im",
    "get_content_region_avail": "im",
    "get_current_context": "im",
    "get_cursor_pos": "im",
    "get_cursor_pos_x": "im",
    "get_cursor_pos_y": "im",
    "get_cursor_screen_pos": "im",
    "get_cursor_start_pos": "im",
    "get_drag_drop_payload": "im",
    "get_draw_data": "im",
    "get_draw_list_shared_data": "im",
    "get_font": "im",
    "get_font_baked": "im",
    "get_font_size": "im",
    "get_font_tex_uv_white_pixel": "im",
    "get_foreground_draw_list": "im",
    "get_frame_count": "im",
    "get_frame_height": "im",
    "get_frame_height_with_spacing": "im",
    "get_id": "im",
    "get_io": "im",
    "get_item_clicked_count_with_single_click_delay": "im",
    "get_item_flags": "im",
    "get_item_id": "im",
    "get_item_rect": "im",
    "get_item_rect_max": "im",
    "get_item_rect_min": "im",
    "get_item_rect_size": "im",
    "get_key_name": "im",
    "get_key_pressed_amount": "im",
    "get_main_viewport": "im",
    "get_mouse_clicked_count": "im",
    "get_mouse_cursor": "im",
    "get_mouse_drag_delta": "im",
    "get_mouse_pos": "im",
    "get_mouse_pos_on_opening_current_popup": "im",
    "get_nav_id": "im",
    "get_nav_ring": "im",
    "get_platform_io": "im",
    "get_scroll_max_x": "im",
    "get_scroll_max_y": "im",
    "get_scroll_x": "im",
    "get_scroll_y": "im",
    "get_state_storage": "im",
    "get_style": "im",
    "get_style_color_name": "im",
    "get_style_color_vec4": "im",
    "get_text_line_height": "im",
    "get_text_line_height_with_spacing": "im",
    "get_time": "im",
    "get_tree_node_to_label_spacing": "im",
    "get_version": "im",
    "get_window_dock_id": "im",
    "get_window_draw_list": "im",
    "get_window_height": "im",
    "get_window_pos": "im",
    "get_window_size": "im",
    "get_window_width": "im",
    "hsv_to_rgb": "widgets.color",
    "im_col32": "im",
    "image": "im",
    "image_button": "im",
    "image_with_bg": "im",
    "indent": "im",
    "input_double": "im",
    "input_float": "im",
    "input_float2": "im",
    "input_float3": "im",
    "input_float4": "im",
    "input_int": "im",
    "input_int2": "im",
    "input_int3": "im",
    "input_int4": "im",
    "input_scalar": "im",
    "input_scalar_n": "im",
    "input_text": "im",
    "input_text_multiline": "im",
    "input_text_with_hint": "im",
    "invisible_button": "im",
    "is_any_item_active": "im",
    "is_any_item_focused": "im",
    "is_any_item_hovered": "im",
    "is_any_mouse_down": "im",
    "is_item_activated": "im",
    "is_item_active": "im",
    "is_item_clicked": "im",
    "is_item_deactivated": "im",
    "is_item_deactivated_after_edit": "im",
    "is_item_edited": "im",
    "is_item_focused": "im",
    "is_item_hovered": "im",
    "is_item_nav_focused": "im",
    "is_item_toggled_open": "im",
    "is_item_toggled_selection": "im",
    "is_item_visible": "im",
    "is_key_chord_pressed": "im",
    "is_key_down": "im",
    "is_key_pressed": "im",
    "is_key_released": "im",
    "is_mouse_clicked": "im",
    "is_mouse_double_clicked": "im",
    "is_mouse_down": "im",
    "is_mouse_dragging": "im",
    "is_mouse_hovering_rect": "im",
    "is_mouse_pos_valid": "im",
    "is_mouse_released": "im",
    "is_mouse_released_with_delay": "im",
    "is_popup_open": "im",
    "is_rect_visible": "im",
    "is_window_appearing": "im",
    "is_window_collapsed": "im",
    "is_window_docked": "im",
    "is_window_focused": "im",
    "is_window_hovered": "im",
    "key_from_dom": "keys",
    "label_text": "im",
    "label_text_v": "im",
    "list_box": "im",
    "load_ini_settings_from_disk": "im",
    "load_ini_settings_from_memory": "im",
    "log_buttons": "im",
    "log_finish": "im",
    "log_text": "im",
    "log_text_v": "im",
    "log_to_clipboard": "im",
    "log_to_file": "im",
    "log_to_tty": "im",
    "mem_alloc": "im",
    "mem_free": "im",
    "menu_item": "im",
    "modifier_name": "events",
    "modifiers_from_canvas": "events",
    "modifiers_from_dom": "keys",
    "nav_tab": "im",
    "new_frame": "im",
    "new_line": "im",
    "next_column": "im",
    "nice_ticks": "widgets.axis",
    "open_popup": "im",
    "open_popup_on_item_click": "im",
    "painter_capabilities": "im",
    "plot_histogram": "im",
    "plot_lines": "im",
    "png_decode": "testing",
    "png_encode": "testing",
    "pop_clip_rect": "im",
    "pop_font": "im",
    "pop_id": "im",
    "pop_item_flag": "im",
    "pop_item_width": "im",
    "pop_style_color": "im",
    "pop_style_var": "im",
    "pop_text_wrap_pos": "im",
    "process_nav_keys": "im",
    "progress_bar": "im",
    "push_clip_rect": "im",
    "push_font": "im",
    "push_id": "im",
    "push_item_flag": "im",
    "push_item_width": "im",
    "push_style_color": "im",
    "push_style_var": "im",
    "push_style_var_x": "im",
    "push_style_var_y": "im",
    "push_text_wrap_pos": "im",
    "radio_button": "im",
    "ratio_from_value": "widgets.sliders",
    "render": "im",
    "reset_mouse_drag_delta": "im",
    "rgb_to_hsv": "widgets.color",
    "rgba_to_floats": "widgets.color",
    "same_line": "im",
    "save_ini_settings_to_disk": "im",
    "save_ini_settings_to_memory": "im",
    "save_png": "testing",
    "screenshot": "testing",
    "selectable": "im",
    "separator": "im",
    "separator_text": "im",
    "set_allocator_functions": "im",
    "set_clipboard_text": "im",
    "set_column_offset": "im",
    "set_column_width": "im",
    "set_current_context": "im",
    "set_cursor_pos": "im",
    "set_cursor_pos_x": "im",
    "set_cursor_pos_y": "im",
    "set_cursor_screen_pos": "im",
    "set_drag_drop_payload": "im",
    "set_item_default_focus": "im",
    "set_item_key_owner": "im",
    "set_item_tooltip": "im",
    "set_item_tooltip_v": "im",
    "set_keyboard_focus_here": "im",
    "set_mouse_cursor": "im",
    "set_nav_cursor_visible": "im",
    "set_nav_id": "im",
    "set_next_frame_want_capture_keyboard": "im",
    "set_next_frame_want_capture_mouse": "im",
    "set_next_item_allow_overlap": "im",
    "set_next_item_open": "im",
    "set_next_item_selection_user_data": "im",
    "set_next_item_shortcut": "im",
    "set_next_item_storage_id": "im",
    "set_next_item_width": "im",
    "set_next_window_auto_resize": "im",
    "set_next_window_bg_alpha": "im",
    "set_next_window_collapsed": "im",
    "set_next_window_content_size": "im",
    "set_next_window_dock_id": "im",
    "set_next_window_focus": "im",
    "set_next_window_pos": "im",
    "set_next_window_scroll": "im",
    "set_next_window_size": "im",
    "set_next_window_size_constraints": "im",
    "set_scroll_from_pos_x": "im",
    "set_scroll_from_pos_y": "im",
    "set_scroll_here_x": "im",
    "set_scroll_here_y": "im",
    "set_scroll_x": "im",
    "set_scroll_y": "im",
    "set_state_storage": "im",
    "set_tab_item_closed": "im",
    "set_tooltip": "im",
    "set_tooltip_v": "im",
    "set_window_collapsed": "im",
    "set_window_focus": "im",
    "set_window_placement": "im",
    "set_window_pos": "im",
    "set_window_size": "im",
    "shortcut": "im",
    "show_about_window": "im",
    "show_debug_log_window": "im",
    "show_demo_window": "im",
    "show_font_selector": "im",
    "show_id_stack_tool_window": "im",
    "show_metrics_window": "im",
    "show_style_editor": "im",
    "show_style_selector": "im",
    "show_user_guide": "im",
    "shrink_widths": "widgets.tabs",
    "slider_angle": "im",
    "slider_float": "im",
    "slider_float2": "im",
    "slider_float3": "im",
    "slider_float4": "im",
    "slider_int": "im",
    "slider_int2": "im",
    "slider_int3": "im",
    "slider_int4": "im",
    "slider_scalar": "im",
    "slider_scalar_n": "im",
    "small_button": "im",
    "spacing": "im",
    "split_label": "im",
    "splitter": "im",
    "splitter_behavior": "im",
    "style_colors_classic": "im",
    "style_colors_dark": "im",
    "style_colors_light": "im",
    "tab_item_button": "im",
    "table_angled_headers_row": "im",
    "table_get_column_count": "im",
    "table_get_column_flags": "im",
    "table_get_column_index": "im",
    "table_get_column_name": "im",
    "table_get_hovered_column": "im",
    "table_get_row_index": "im",
    "table_get_sort_specs": "im",
    "table_header": "im",
    "table_headers_row": "im",
    "table_next_column": "im",
    "table_next_row": "im",
    "table_set_bg_color": "im",
    "table_set_column_enabled": "im",
    "table_set_column_index": "im",
    "table_set_column_order": "im",
    "table_setup_column": "im",
    "table_setup_scroll_freeze": "im",
    "text": "im",
    "text_colored": "im",
    "text_colored_v": "im",
    "text_disabled": "im",
    "text_disabled_v": "im",
    "text_link": "im",
    "text_link_open_url": "im",
    "text_unformatted": "im",
    "text_v": "im",
    "text_wrapped": "im",
    "text_wrapped_v": "im",
    "tree_node": "im",
    "tree_node_ex": "im",
    "tree_node_ex_v": "im",
    "tree_node_get_open": "im",
    "tree_node_v": "im",
    "tree_pop": "im",
    "tree_push": "im",
    "trim_decorations": "widgets.inputs",
    "unindent": "im",
    "v_slider_float": "im",
    "v_slider_int": "im",
    "v_slider_scalar": "im",
    "value": "im",
    "value_from_ratio": "widgets.sliders",
    "wrap_lines": "widgets.text",
}


def __getattr__(name: str):
    """Resolve a ported control lazily, from whichever family owns it.

    Why lazily, and why not ``from .tables import *`` at the top: importing
    twenty-odd modules to put one slider on screen costs every host that time,
    and the browser build pays it on load. The families are independent, so a
    name is resolved by asking each in turn and the module is imported only
    when something actually reaches for one of its controls.

    Parameters
    ----------
    name : str
        The attribute being looked up.

    Returns
    -------
    object
        The control class or helper, which is then cached on the module so the
        search happens once per name.

    Raises
    ------
    AttributeError
        If no family exports it.
    """
    import importlib

    module_name = _NAME_TO_MODULE.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = importlib.import_module(f".{module_name}", __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list:
    """List the eagerly-exported names plus every ported control.

    Returns
    -------
    list of str
        Sorted names, so tab-completion in the console sees the whole toolkit
        rather than only the ones that are imported eagerly.
    """
    import importlib

    names = set(__all__) | {"CONTROL_MODULES"}
    for module_name in CONTROL_MODULES:
        module = importlib.import_module(f".{module_name}", __name__)
        names.update(getattr(module, "__all__", ()))
    return sorted(names)
