"""Colormaps and colour names, with no dependency.

One home for the colour tables an application draws data with -- a heatmap's
lookup table, a scatter's per-value colour, a colour bar -- and for parsing
the colour spellings plot code uses (``"steelblue"``, ``"#1f77b4"``, ``"C3"``,
``(0.2, 0.4, 0.6)``).

.. code-block:: python

    from emtk import colormaps

    cmap = colormaps.get("viridis")
    cmap(0.5)                         # (r, g, b, a), floats in 0..1
    colormaps.lookup_table("magma")   # 256 (r, g, b, a) byte tuples
    colormaps.to_rgba("C1", alpha=0.5)

The tables live in ``colormaps.json`` beside this module (generated by
``tools/build_colormaps.py``; licences in ``licenses/colormaps.txt``): the
perceptual maps (viridis, magma, inferno, plasma, cividis, turbo), Kovesi's
CET maps, and the classic ones (gray, hot, jet, RdBu, coolwarm, ...). Any name
takes an ``_r`` suffix for the reversed map.

**Lookup semantics are matplotlib's**, so code ported from it keeps its
pictures: a float ``x`` in ``[0, 1]`` selects entry ``int(x * N)`` of an
``N``-entry table (clipped to the ends), an *integer* selects that entry, and
NaN is transparent black. Arrays are accepted wherever a scalar is, and are
mapped through numpy when numpy is importable; numpy is never required.
"""

from __future__ import annotations

import functools
import json
import math
import pathlib
from typing import Any, Iterable, Sequence

__all__ = [
    "Colormap",
    "get",
    "has",
    "lookup_table",
    "names",
    "stops",
    "to_hex",
    "to_rgb",
    "to_rgba",
    "to_rgba_bytes",
]

_DATA = pathlib.Path(__file__).resolve().with_name("colormaps.json")

#: Names that are spelled two ways in the wild.
_ALIASES = {"grey": "gray", "Grays": "Greys", "greys": "Greys"}

#: The transparent colour NaN maps to, as matplotlib's "bad" colour does.
_BAD = (0.0, 0.0, 0.0, 0.0)


@functools.lru_cache(maxsize=1)
def _document() -> dict:
    return json.loads(_DATA.read_text(encoding="utf-8"))


def _hex_to_rgb(text: str) -> tuple[float, float, float]:
    return tuple(int(text[i:i + 2], 16) / 255.0 for i in (1, 3, 5))  # type: ignore[return-value]


def _resolve(name: str) -> tuple[str, bool]:
    """``(table name, reversed)`` for *name*, or raise ``KeyError``."""
    maps = _document()["maps"]
    key = str(name)
    reverse = False
    if key not in maps and key not in _ALIASES and key.endswith("_r"):
        key, reverse = key[:-2], True
    key = _ALIASES.get(key, key)
    if key not in maps:
        raise KeyError(f"no colormap named {name!r}")
    return key, reverse


def names() -> list[str]:
    """Every colormap name, sorted case-insensitively (``_r`` variants implied)."""
    return list(_document()["maps"])


def has(name: str) -> bool:
    """Whether *name* (optionally ``_r``-suffixed) is a known colormap."""
    try:
        _resolve(name)
    except KeyError:
        return False
    return True


@functools.lru_cache(maxsize=256)
def stops(name: str) -> tuple[tuple[float, float, float], ...]:
    """The map's RGB stops, 0..1, evenly spaced over ``[0, 1]``.

    Raises
    ------
    KeyError
        When no such colormap exists.
    """
    key, reverse = _resolve(name)
    values = tuple(_hex_to_rgb(h) for h in _document()["maps"][key]["stops"])
    return tuple(reversed(values)) if reverse else values


def _is_qualitative(name: str) -> bool:
    key, _ = _resolve(name)
    return bool(_document()["maps"][key].get("qualitative"))


def _interpolate(points: Sequence[tuple[float, float, float]], t: float) -> tuple[float, ...]:
    """Linear interpolation of evenly spaced *points* at ``t`` in ``[0, 1]``."""
    if len(points) == 1:
        return points[0]
    position = min(max(t, 0.0), 1.0) * (len(points) - 1)
    low = min(int(position), len(points) - 2)
    frac = position - low
    a, b = points[low], points[low + 1]
    return tuple(a[c] + (b[c] - a[c]) * frac for c in range(3))


@functools.lru_cache(maxsize=256)
def _table(name: str, n: int, gamma: float) -> tuple[tuple[float, float, float, float], ...]:
    points = stops(name)
    if _is_qualitative(name):
        # A palette is its colours; resampling one would invent blends.
        return tuple((*p, 1.0) for p in points)
    size = max(2, int(n))
    rows = []
    for i in range(size):
        rgb = _interpolate(points, i / (size - 1))
        if gamma != 1.0:
            rgb = tuple(c ** gamma for c in rgb)
        rows.append((*rgb, 1.0))
    return tuple(rows)


def lookup_table(name: str, n: int = 256, gamma: float = 1.0) -> list[tuple[int, int, int, int]]:
    """``n`` RGBA byte tuples sampling *name* evenly from 0 to 1.

    A qualitative map (tab10, a palette) returns its own colours whatever
    ``n`` is. ``gamma`` raises each channel to that power.

    Raises
    ------
    KeyError
        When no such colormap exists.
    """
    return [tuple(int(round(c * 255.0)) for c in row) for row in _table(name, int(n), float(gamma))]  # type: ignore[misc]


def _numpy():
    try:
        import numpy  # noqa: PLC0415

        return numpy
    except ImportError:  # pragma: no cover - numpy is optional
        return None


class Colormap:
    """A colormap as a callable, spelled like matplotlib's.

    Parameters
    ----------
    name : str
        A name from :func:`names`, optionally ``_r``-suffixed.
    n : int
        Entries in the lookup table (a qualitative map keeps its own count).
    """

    def __init__(self, name: str, n: int = 256):
        _resolve(name)
        self.name = str(name)
        self._rows = _table(self.name, int(n), 1.0)
        self.N = len(self._rows)

    def __repr__(self) -> str:
        return f"Colormap({self.name!r}, N={self.N})"

    def __eq__(self, other: object) -> bool:
        return isinstance(other, Colormap) and other.name == self.name and other.N == self.N

    def __hash__(self) -> int:
        return hash((self.name, self.N))

    def reversed(self) -> Colormap:
        """The same map run backwards (``name_r``)."""
        name = self.name[:-2] if self.name.endswith("_r") and has(self.name[:-2]) else self.name + "_r"
        return Colormap(name, self.N)

    def _index(self, x: float) -> int:
        return min(max(int(x * self.N), 0), self.N - 1)

    def _scalar(self, x: Any, alpha: float | None) -> tuple[float, float, float, float]:
        integral = isinstance(x, int) or getattr(getattr(x, "dtype", None), "kind", "") in "iu"
        if isinstance(x, bool) or not integral or not hasattr(x, "__index__"):
            value = float(x)
            if math.isnan(value):
                return _BAD
            row = self._rows[self._index(value)]
        else:
            row = self._rows[min(max(int(x), 0), self.N - 1)]
        return row if alpha is None else (*row[:3], float(alpha))

    def __call__(self, x: Any, alpha: float | None = None, bytes: bool = False) -> Any:  # noqa: A002
        """Map *x* to RGBA.

        A scalar gives a tuple, anything array-like an array of shape
        ``(*x.shape, 4)`` (numpy) or a list of tuples (no numpy). ``bytes``
        returns 0..255 integers instead of 0..1 floats.
        """
        np = _numpy()
        is_array = np is not None and isinstance(x, np.ndarray)
        if not is_array and not isinstance(x, (list, tuple)):
            row = self._scalar(x, alpha)
            return tuple(int(round(c * 255)) for c in row) if bytes else row
        if np is None:
            rows = [self._scalar(v, alpha) for v in x]
            return [tuple(int(round(c * 255)) for c in r) for r in rows] if bytes else rows
        values = np.asarray(x)
        table = np.asarray(self._rows, dtype=float)
        if np.issubdtype(values.dtype, np.integer):
            out = table[np.clip(values, 0, self.N - 1)]
        else:
            values = values.astype(float)
            bad = np.isnan(values)
            index = np.clip((np.nan_to_num(values) * self.N).astype(np.int64), 0, self.N - 1)
            out = table[index]
            out[bad] = _BAD
        if alpha is not None:
            out[..., 3] = float(alpha)
        if bytes:
            return np.round(out * 255.0).astype(np.uint8)
        return out

    def colors(self, n: int) -> list[tuple[float, float, float, float]]:
        """*n* colours sampled evenly from one end to the other."""
        if n <= 1:
            return [self._scalar(0.0, None)]
        return [self._scalar(i / (n - 1), None) for i in range(n)]


@functools.lru_cache(maxsize=128)
def get(name: str, n: int = 256) -> Colormap:
    """The :class:`Colormap` called *name* (``KeyError`` when unknown)."""
    return Colormap(name, n)


# ---------------------------------------------------------------- colours --


def _named() -> dict[str, str]:
    return _document()["named"]


def to_rgba(colour: Any, alpha: float | None = None) -> tuple[float, float, float, float]:
    """Parse *colour* into an ``(r, g, b, a)`` tuple of floats in 0..1.

    Accepted: a name (CSS4, ``"r"``/``"k"``/..., ``"C0"``..``"C9"``,
    ``"tab:blue"``), ``"#rgb"``/``"#rrggbb"``/``"#rrggbbaa"``, a grey level as
    a string (``"0.5"``), ``"none"`` (transparent), and a 3- or 4-sequence
    of floats in 0..1 -- or of integers in 0..255, which is how Qt-era code
    spells colours. *alpha*, when given, replaces the alpha channel.

    Raises
    ------
    ValueError
        When *colour* cannot be read as a colour.
    """
    rgba = _parse(colour)
    if alpha is not None:
        rgba = (*rgba[:3], float(alpha))
    return rgba


def _parse(colour: Any) -> tuple[float, float, float, float]:
    if isinstance(colour, str):
        text = colour.strip()
        lower = text.lower()
        if lower == "none":
            return (0.0, 0.0, 0.0, 0.0)
        named = _named()
        value = named.get(text, named.get(lower))
        if value is not None:
            return (*_hex_to_rgb(value), 1.0)
        if text.startswith("#"):
            digits = text[1:]
            if len(digits) in (3, 4):
                digits = "".join(2 * c for c in digits)
            if len(digits) in (6, 8):
                try:
                    channels = [int(digits[i:i + 2], 16) / 255.0 for i in range(0, len(digits), 2)]
                except ValueError:
                    pass
                else:
                    return tuple(channels) + ((1.0,) if len(channels) == 3 else ())  # type: ignore[return-value]
        try:
            level = float(text)
        except ValueError:
            raise ValueError(f"not a colour: {colour!r}") from None
        if 0.0 <= level <= 1.0:
            return (level, level, level, 1.0)
        raise ValueError(f"a grey level is 0..1, got {colour!r}")
    if isinstance(colour, Iterable):
        channels = list(colour)
        if len(channels) not in (3, 4):
            raise ValueError(f"a colour has 3 or 4 channels, got {colour!r}")
        if all(isinstance(c, int) and not isinstance(c, bool) for c in channels) and any(
            c > 1 for c in channels
        ):
            channels = [c / 255.0 for c in channels]
        values = [float(c) for c in channels]
        if any(not 0.0 <= c <= 1.0 for c in values):
            raise ValueError(f"colour channels are 0..1 (or integers 0..255), got {colour!r}")
        return tuple(values) + ((1.0,) if len(values) == 3 else ())  # type: ignore[return-value]
    raise ValueError(f"not a colour: {colour!r}")


def to_rgb(colour: Any) -> tuple[float, float, float]:
    """:func:`to_rgba` without the alpha channel."""
    return to_rgba(colour)[:3]  # type: ignore[return-value]


def to_rgba_bytes(colour: Any, alpha: float | None = None) -> tuple[int, int, int, int]:
    """:func:`to_rgba` as 0..255 integers."""
    return tuple(int(round(c * 255.0)) for c in to_rgba(colour, alpha))  # type: ignore[return-value]


def to_hex(colour: Any, keep_alpha: bool = False) -> str:
    """``"#rrggbb"`` (or ``"#rrggbbaa"`` with *keep_alpha*) for *colour*."""
    channels = to_rgba(colour)
    if not keep_alpha:
        channels = channels[:3]
    return "#" + "".join(f"{int(round(c * 255.0)):02x}" for c in channels)
